# Generated by Django 4.1.4 on 2023-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('institute', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('trainer_mode', models.CharField(max_length=100)),
            ],
        ),
    ]
