# Generated by Django 4.1.4 on 2023-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsolutionsapp', '0002_studentsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
