# Generated by Django 4.1.4 on 2023-01-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsolutionsapp', '0003_studentfeedbackdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentfeedbackData',
        ),
    ]
